appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c32d1a93aeb3c070044c6b4
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: rs54D4YD80ZLSqjyl3DdjwrcSar/wI1BQUeQE+WWYtHJGOhshfAr+aSoicO11iEHLRv3Gin6i1TadbCG+cQREtdr5uLvWIO2f9d+NtJQtv+3mY5hqD5cvF+sLYKb++gWVzGQQfYT5lc5pPlhuXiZ07iC/Jxe+w8vuuk1TB5G+2mY+kUZfw2w2x4XPlJWjUK//R7TTwqkZ6fYbbQF8pZCvocGVDYNOA4zGgjaWnJ+T3KDhum1HYWr2z7sn45kcS/FgWamP2iZucH2b9+SusykRFh0auvahq3Rr4zgZSzmt91/OgqJdoUZLeg5WqiOzJ0hJXlthDOowD+FkQe8ZKvIfMrn0S5PZuAJQF8fkUDNdRYibKbKzA+TCmI3Sul9hzTrVPNElyR0iJDbssdcX2zKMw11oMOYkDk1uzPeFwUrTcvle+eT6IpHJNfb1Eog6N1NY73oXr9q1HAIuU/IMa+P41lfhi2gQ+zrv4b0aEM2ABTbyVOnZHkR8uV/WrHo7sOS4mq5ees/uuTmA4PQU781rVNxCceEKL/Pfl1elkgYUSj+DTrWNn+vH3l39kTHlz1xvFeAVklMOYGHJ01Jag6JOTGrWHwXUDEFcy8k8N7nhT3htTSFMF/kzWLuj/c7E2MnJdrszf3miRPhfVSWKnxQP6ke2PUQQD7RkbDD8TupW0M=}
